module.exports = [
  {
    title: "OFFEO SG",
    logo: require("@/assets/images/experience/offeo.jpg"),
    description:
      "As a Frontend Developer, collaborate together with art director to develop beautiful UIs & features to give remarkable experience for users. Integrate API from backend to exchange data within database. Contributed to increased SEO & web performance of OFFEO. Apply unit testings across OFFEO sites with Jest. Building scalability by implementing clean & readable code methodology. Develop internal site within fullstack development with Inertia-Vue-Laravel-MySQL.",
    skills: [
      "Vue.js",
      "Vuex",
      "Nuxt.js",
      "REST API",
      "SEO & Web Performance",
      "Git (Bitbucket & Github)",
      "Gitahead",
      "SCSS/SASS",
      "UNIX System (Linux)",
      "Webpack",
      "Inertia.js",
      "Laravel",
      "MYSQL",
      "Vuetify",
      "Babel",
    ],
  },
  {
    title: "Infinity Batam (Exotica Batam)",
    logo: require("@/assets/images/experience/infinity.jpeg"),
    description:
      "As Senior Graphic Designer, work closely to founder to bring 3D interior & graphic design ideas into reality. Brief & prepare production team on material needs & production schedules for a successful event setup, held events & build relationship with big companies like RIWAY, JOTUN, SIIX, PHILIPS, etc.",
    skills: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Coreldraw",
      "Sketchup",
      "Lumion",
      "Vray",
      "Adobe XD",
      "Adobe Premier Pro",
      "Adobe After Effects",
      "Teamwork & Management",
      "Interior & Graphic Design",
      "Microsoft Office",
    ],
  },
  {
    title: "Impact Byte Fullstack Javascript Bootcamp",
    logo: require("@/assets/images/experience/impactbyte.png"),
    description:
      "Intensive Bootcamp in Fullstack Major. Learnt frontend, backend & web deployment lessons to become a certified Fullstack Javascript Developer. Doing practices, trainings & finish final project with presentation of our team's software to fellow recruiters from Indonesia & Singapore.",
    skills: [
      "React.js",
      "React Redux",
      "Express.js",
      "MongoDB",
      "Node.js",
      "AWS",
      "Heroku",
      "Vercel",
      "SCSS & CSS",
      "Javascript",
      "Trello",
      "Github",
      "Responsive Web Design",
    ],
  },
  {
    title: "Glints Web Development Instructor",
    logo: require("@/assets/images/experience/glints.png"),
    description:
      "Provide guidance through newcomers in web development. Become a mentor of javascript & web development. Share best practices, experience, give live code tests & live code trainings.",
    skills: ["Mentoring", "Javascript", "Web Development"],
  },
  {
    title: "Fingerfast Laboratory",
    logo: require("@/assets/images/experience/ff.jpg"),
    description:
      "As Intern Graphic Designer, creating Designs, create videos, collaborate in online-queue-ticket-booking application for hospital, create advertisements to support the sales growth of our company & provide support to the founder.",
    skills: [
      "Adobe After Effects",
      "Adobe Premier Pro",
      "Photography & Videography",
      "Digital Marketing",
      "Photoshop",
      "Coreldraw",
      "Sketchup",
    ],
  },
  {
    title: "Leader of Maitreyawira's English Debate Club",
    logo: require("@/assets/images/experience/leader.png"),
    description:
      "Managing Juniors, improve talents, participated in several competitions with teammates & win some, support this community and each part of team inside to their best versions.",
    skills: [
      "Leadership",
      "Teamwork",
      "Management",
      "English Skill",
      "Public Speaking",
      "Presentation Skills",
    ],
  },
  {
    title: "Collaboration with Exive Interior",
    logo: require("@/assets/images/experience/exive.jpeg"),
    description:
      "Creating 3D Interior & Exterior of 'MICHS BATIK' store, an Interior with Batik & elegant theme located in Jakarta, Indonesia.",
    skills: [
      "Interior & Exterior Design",
      "Lumion",
      "Sketchup",
      "Vray",
      "Photoshop",
    ],
  },
];
