/*
--- Total Portofolio = 19
*/

module.exports = [
  {
    title: "Asia-Property",
    description:
      "Beautiful & modern real estate website that developed within full-stack development until deployment all by myself, designed purely with SCSS based from ideas i received from themeforest.com & dribbble.com.",
    thumbnail: require("@/assets/images/works/asia01.png"),
    year: 2021,
    tags: ["ReactJS", "Fullstack"],
    website: "https://asiaproperty.netlify.app/",
    previews: [
      require("@/assets/images/works/asia01.png"),
      require("@/assets/images/works/asia02.png"),
      require("@/assets/images/works/asia03.png"),
      require("@/assets/images/works/asia04.png"),
      require("@/assets/images/works/asia05.png"),
      require("@/assets/images/works/asia06.png"),
      require("@/assets/images/works/asia07.png"),
      require("@/assets/images/works/asia08.png"),
    ],
    skills: [
      "ReactJS",
      "ReactRedux",
      "ExpressJS",
      "MongoDB",
      "Cookie",
      "Heroku",
      "REST API",
      "SCSS",
      "Fullstack web development",
      "Icomoon",
      "Github",
    ],
  },
  {
    title: "Asia-Property (Admin Site)",
    description:
      "An excellent & convenient admin site developed within full-stack development. Inspired by admin website ideas from dribbble.com, created flawless interface that brings good experience to users.",
    thumbnail: require("@/assets/images/works/asia-admin01.png"),
    year: 2022,
    tags: ["ReactJS", "Fullstack"],
    website: "https://asiaproperty.netlify.app/admin?is_visitor=true",
    previews: [
      require("@/assets/images/works/asia-admin01.png"),
      require("@/assets/images/works/asia-admin02.png"),
      require("@/assets/images/works/asia-admin03.png"),
      require("@/assets/images/works/asia-admin04.png"),
      require("@/assets/images/works/asia-admin05.png"),
      require("@/assets/images/works/asia-admin06.png"),
      require("@/assets/images/works/asia-admin07.png"),
      require("@/assets/images/works/asia-admin08.png"),
      require("@/assets/images/works/asia-admin09.png"),
      require("@/assets/images/works/asia-admin10.png"),
      require("@/assets/images/works/asia-admin11.png"),
      require("@/assets/images/works/asia-admin12.png"),
    ],
    skills: [
      "ReactJS",
      "ReactRedux",
      "ExpressJS",
      "MongoDB",
      "Cookie",
      "Heroku",
      "REST API",
      "SCSS",
      "Fullstack Web Development",
      "Apexchart.js",
      "Icomoon",
      "Github",
    ],
  },
  {
    title: "GlobalUI CSS Framework",
    description:
      "A CSS Framework & Components Library that is created with Vue.js. Support the usage for Vue.js or Nuxt.js developers. 1 of my best works so far, a system example for agencies that want to have consistent components / UI. Efficient for future changes & a great tool for teamwork culture.",
    thumbnail: require("@/assets/images/works/css-framework1.png"),
    year: 2021,
    tags: ["VueJS", "NPM"],
    website: "https://global-ui-docs.netlify.app/",
    npmWebsite: "https://www.npmjs.com/package/global-ui",
    previews: [
      require("@/assets/images/works/css-framework1.png"),
      require("@/assets/images/works/css-framework2.png"),
      require("@/assets/images/works/css-framework3.png"),
      require("@/assets/images/works/css-framework4.png"),
    ],
    skills: [
      "VueJS",
      "Storybook",
      "NPM Package Deployment",
      "Component Documentation System",
      "Component Library System",
      "Animation Loader System",
      "Icomoon",
      "SCSS",
      "Github",
    ],
  },
  {
    title: "Laravel Fullstack Community Website",
    description:
      "An Interactive Fullstack Laravel Color Palette Community Website Made with MySQL, Laravel Blade, Laravel & Tailwind.css. Integrated with gmail mailing system & deployed to heroku included database.",
    thumbnail: require("@/assets/images/works/laravel-fullstack-app2.png"),
    year: 2021,
    tags: ["Laravel-PHP", "Fullstack"],
    website: "https://laravel-fd-color-palette.herokuapp.com/",
    previews: [
      require("@/assets/images/works/laravel-fullstack-app1.png"),
      require("@/assets/images/works/laravel-fullstack-app2.png"),
      require("@/assets/images/works/laravel-fullstack-app3.png"),
      require("@/assets/images/works/laravel-fullstack-app4.png"),
      require("@/assets/images/works/laravel-fullstack-app5.png"),
      require("@/assets/images/works/laravel-fullstack-app6.png"),
      require("@/assets/images/works/laravel-fullstack-app7.png"),
      require("@/assets/images/works/laravel-fullstack-app8.png"),
      require("@/assets/images/works/laravel-fullstack-app9.png"),
    ],
    skills: [
      "Laravel & PHP",
      "MYSQL",
      "Laravel Blade",
      "Tailwind.css",
      "Gmail Mailing System",
      "Heroku Deployment",
      "Fullstack Web Development",
    ],
  },
  {
    title: "Web Performance & SEO Improvements Studycase",
    description:
      "Web performance & SEO improvements done on my personal website (chenfrederick.com). Can see the snapshots for before-after of the web performance result inspected with Lighthouse & SEO result where my website exist in page 1 at google search result.",
    thumbnail: require("@/assets/images/works/web-performance-after.jpeg"),
    year: 2021,
    tags: ["SEO", "Web Performance"],
    website: "https://www.chenfrederick.com/",
    previews: [
      require("@/assets/images/works/web-performance-before.png"),
      require("@/assets/images/works/web-performance-after.jpeg"),
      require("@/assets/images/works/seo-result.png"),
      require("@/assets/images/works/personal-web-3.jpeg"),
    ],
    skills: [
      "Web Performance",
      "Web Optimization",
      "SEO",
      "VueJS",
      "Lighthouse Inspection",
    ],
  },
  {
    title: "React E-Commerce",
    description:
      "Full Version of ReactJS & Redux E-Commerce made by Fullstack Development (Frontend, Backend until Deployments), Inspiration based on Best Seller E-Commerce app in theme forest (PickBazar). When user register & data stored to database, CRUD products of admin, and everything that runs here was made by me. Check out this cool E-commerce!",
    thumbnail: require("@/assets/images/works/react-ecommerce1.png"),
    year: 2020,
    tags: ["ReactJS", "Fullstack"],
    website: "https://s2-boutique.netlify.app/",
    previews: [
      require("@/assets/images/works/react-ecommerce1.png"),
      require("@/assets/images/works/react-ecommerce2.png"),
      require("@/assets/images/works/react-ecommerce3.png"),
      require("@/assets/images/works/react-ecommerce4.png"),
      require("@/assets/images/works/react-ecommerce5.png"),
    ],
    skills: [
      "ReactJS",
      "React Redux",
      "ExpressJS",
      "MongoDB",
      "Heroku",
      "AWS",
      "Cloudflare",
      "REST API",
      "Fullstack Web Development",
      "SCSS",
      "Github",
    ],
  },
  {
    title: "ChenFrederick.com (Personal Web)",
    description:
      "My latest personal website, at here i try to share with you more about myself, my portofolios, my experiences and also my skills. Here, you can also access my personal web in phone & set to dark mode if you need! Let's get to know each other.",
    thumbnail: require("@/assets/images/works/personal-web.png"),
    year: 2021,
    tags: ["VueJS", "Dark Mode"],
    website: null,
    previews: [
      require("@/assets/images/works/personal-web.png"),
      require("@/assets/images/works/personal-web-2.png"),
      require("@/assets/images/works/personal-web-3.jpeg"),
    ],
    skills: [
      "VueJS",
      "Vuex",
      "Dark Mode",
      "Responsive Web App",
      "Animation Loader System",
      "SCSS",
      "Website Domain Handling & Deployment",
      "Cloudflare",
      "Icomoon",
      "Github",
    ],
  },
  {
    title: "Vue Firebase Fullstack Apps",
    description:
      "A Vue.js (Frontend Side) + Firebase (Backend Side) website that consist customer management system + todoapp. It is able to handle image uploads, CRUD of database column & clearing of uploaded image in database. This VueFire app was deployed as a live website that can be accessed online.",
    thumbnail: require("@/assets/images/works/vue-firebase1.png"),
    year: 2021,
    tags: ["VueJS-Firebase", "Fullstack"],
    website: "https://fd-vue-firebase.web.app/#/",
    previews: [
      require("@/assets/images/works/vue-firebase1.png"),
      require("@/assets/images/works/vue-firebase2.png"),
    ],
    skills: [
      "VueJS",
      "Firebase",
      "Fullstack Web Development",
      "Firebase Integration",
      "Firebase Multisite Deployment",
      "SCSS",
      "Github",
    ],
  },
  {
    title: "PHP + MYSQL - Payroll Website",
    description:
      "A Pure PHP & MYSQL Fullstack payroll website. Able to handle authentication, pdf exports, database connections, and many things across users activity on the web.",
    thumbnail: require("@/assets/images/works/payroll01.jpeg"),
    year: 2020,
    tags: ["PHP-MYSQL", "Fullstack"],
    website: null,
    github: "https://github.com/Frederick-88/PHP-SQL-PAYROLL-WEB",
    previews: [
      require("@/assets/images/works/payroll01.jpeg"),
      require("@/assets/images/works/payroll02.jpeg"),
      require("@/assets/images/works/payroll03.jpeg"),
      require("@/assets/images/works/payroll04.jpeg"),
      require("@/assets/images/works/payroll05.jpeg"),
      require("@/assets/images/works/payroll06.jpeg"),
      require("@/assets/images/works/payroll07.jpeg"),
      require("@/assets/images/works/payroll08.jpeg"),
      require("@/assets/images/works/payroll09.jpeg"),
    ],
    skills: [
      "PHP",
      "MYSQL",
      "Bootstrap",
      "Fullstack Web Development",
      "CSS",
      "PDF Export System",
    ],
  },
  {
    title: "Weatherpedia (PWA)",
    description:
      "Weatherpedia provides weather informations in Singapore ( by default ) and show current weather with attractive & different designs, made with PWA development-model ( Progressive Web App ). With this, user can download the web into a mobile app for a very small size of 332 kb. then user also can search other city to seek their weather information at here. Supported by API from https://api.openweathermap.org",
    thumbnail: require("@/assets/images/works/weatherpedia-pwa1.png"),
    year: 2021,
    tags: ["ReactJS", "PWA"],
    website: "https://weatherpedia.netlify.app/",
    previews: [
      require("@/assets/images/works/weatherpedia-pwa1.png"),
      require("@/assets/images/works/weatherpedia-pwa2.png"),
      require("@/assets/images/works/weatherpedia-pwa3.png"),
      require("@/assets/images/works/weatherpedia-pwa4.png"),
      require("@/assets/images/works/weatherpedia-pwa5.png"),
      require("@/assets/images/works/weatherpedia-pwa6.png"),
    ],
    skills: [
      "ReactJS",
      "Progressive Web App (PWA)",
      "REST API",
      "Responsive Web App",
      "SCSS",
      "Github",
    ],
  },
  {
    title: "React & Vue Unit Testing Sample Practices",
    description:
      "React & Vue Unit Testing Sample Practices (for react - https://github.com/Frederick-88/react-unit-testing) & (for vue - https://github.com/Frederick-88/vue-unit-testing)",
    thumbnail: require("@/assets/images/works/vue-react-unit-test.png"),
    year: 2021,
    tags: ["ReactJS", "VueJS"],
    website: null,
    github: "https://github.com/Frederick-88",
    previews: [require("@/assets/images/works/vue-react-unit-test.png")],
    skills: ["VueJS", "ReactJS", "Unit Testing"],
  },
  {
    title: "Vue Text to Speech AI",
    description:
      "An AI created on Vue web application about text to speech convertion. It's accessible on any screen size since its a responsive web app which also has playback speed and gender voice options for users to use around.",
    thumbnail: require("@/assets/images/works/vue-text-to-speech.png"),
    year: 2022,
    tags: ["VueJS", "Responsive Web App"],
    website: "https://vue-text-to-speech.netlify.app/",
    previews: [require("@/assets/images/works/vue-text-to-speech.png")],
    skills: ["VueJS", "AI", "SCSS", "Responsive Web App"],
  },
  {
    title: "FD-Technologies (Personal Web)",
    description:
      "My previous personal web created with ReactJS & Bootstrap. Accessible with any device since its a responsive web app.",
    thumbnail: require("@/assets/images/works/fdtech01.png"),
    year: 2020,
    tags: ["ReactJS", "Responsive Web App"],
    website: "https://fd-tech.netlify.app/",
    previews: [
      require("@/assets/images/works/fdtech01.png"),
      require("@/assets/images/works/fdtech02.png"),
      require("@/assets/images/works/fdtech03.png"),
      require("@/assets/images/works/fdtech04.png"),
    ],
    skills: [
      "ReactJS",
      "Responsive Web App",
      "SCSS",
      "Website Domain Handling & Deployment",
      "Cloudflare",
      "Bootstrap",
      "FontAwesome",
      "Github",
    ],
  },
  {
    title: "SmartLocal Gists Page",
    description:
      "This is 1 of the test from a company based on Singapore. With a github opensource api given (https://api.github.com/gists/public),then creatively display it to users. Here, user can see any topic of github gists, search based on github usernames, favourite gists, look through gists author, etc.",
    thumbnail: require("@/assets/images/works/smartlocal1.png"),
    year: 2020,
    tags: ["ReactJS", "REST API"],
    website: "https://github-gists.netlify.app/",
    previews: [
      require("@/assets/images/works/smartlocal1.png"),
      require("@/assets/images/works/smartlocal2.png"),
      require("@/assets/images/works/smartlocal3.png"),
      require("@/assets/images/works/smartlocal4.png"),
    ],
    skills: [
      "ReactJS",
      "Local Storage",
      "REST API",
      "Font Awesome",
      "React Toastify",
      "SCSS",
      "Github",
    ],
  },
  {
    title: "Technical Test - Photo Album Website",
    description:
      'A Sample Technical Test (Real-Life) of ReactJS (Responsive Web App) to Fetch API from an Opensource API - "https://jsonplaceholder.typicode.com".',
    thumbnail: require("@/assets/images/works/photo-album-test-01.png"),
    year: 2021,
    tags: ["ReactJS", "Responsive Web App"],
    website: "https://fd-photoalbum.netlify.app/",
    previews: [
      require("@/assets/images/works/photo-album-test-01.png"),
      require("@/assets/images/works/photo-album-test-02.png"),
      require("@/assets/images/works/photo-album-test-03.png"),
      require("@/assets/images/works/photo-album-test-04.png"),
      require("@/assets/images/works/photo-album-test-05.png"),
    ],
    skills: ["ReactJS", "Responsive Web App", "REST API", "SCSS", "Github"],
  },
  {
    title: "Circle Messenger",
    description:
      "A Real-Time messenger app which is a team final project in glints academy bootcamp. Here, users could send image, documents and even show expressions with emoji here!",
    thumbnail: require("@/assets/images/works/circle-messenger1.png"),
    year: 2020,
    tags: ["ReactJS", "Fullstack"],
    website: null,
    previews: [
      require("@/assets/images/works/circle-messenger1.png"),
      require("@/assets/images/works/circle-messenger2.png"),
    ],
    skills: [
      "ReactJS",
      "React Redux",
      "Socket.io",
      "Google Cloud",
      "REST API",
      "ExpressJS",
      "MongoDB",
      "Font Awesome",
      "SCSS",
      "Github",
    ],
  },
  {
    title: "Kos45 - No Bullying Community Web",
    description:
      "A Responsive Web App created with ReactJS about no bullying community.",
    thumbnail: require("@/assets/images/works/kos45-01.png"),
    year: 2020,
    tags: ["ReactJS", "Responsive Web App"],
    website: "https://kos45.netlify.app/#/",
    previews: [
      require("@/assets/images/works/kos45-01.png"),
      require("@/assets/images/works/kos45-02.png"),
      require("@/assets/images/works/kos45-03.png"),
    ],
    skills: ["ReactJS", "Responsive Web App", "FontAwesome", "SCSS", "Github"],
  },
  {
    title: "Pair Programming Test - PokeAPI",
    description:
      'A Sample Pair Programming Test (Real-Life) of ReactJS to Fetch API from an Opensource API - "https://pokeapi.co/". With the duration of 30 minutes to create then stop the development.',
    thumbnail: require("@/assets/images/works/pair-programming-test-01.png"),
    year: 2021,
    tags: ["ReactJS", "REST API"],
    website: "https://pokeapi-test.netlify.app/",
    previews: [require("@/assets/images/works/pair-programming-test-01.png")],
    skills: ["ReactJS", "REST API", "SCSS", "Github"],
  },
  {
    title: "AzurDrones with Vue",
    description:
      "A drone company website which made with VueJS. Interactive Gradient & Animated UI with Fantastic Toast Notifications!",
    thumbnail: require("@/assets/images/works/azurdrones1.png"),
    year: 2020,
    tags: ["VueJS", "Vuex"],
    website: "https://azurdrones.netlify.app/",
    previews: [
      require("@/assets/images/works/azurdrones1.png"),
      require("@/assets/images/works/azurdrones2.png"),
    ],
    skills: [
      "VueJS",
      "Vuex",
      "Vue Toastification",
      "Vue Owl Carousel",
      "Font Awesome",
      "Github",
    ],
  },
];
